#!/usr/bin/env python3
"""
Add zh-Hans (Simplified Chinese) translations to the main app's Localizable.xcstrings.
For each string entry that doesn't already have zh-Hans, add it.
"""

import json
import sys

FILE = "/Users/qiming/workspace/typewhisper-mac/TypeWhisper/Resources/Localizable.xcstrings"

# Complete translation dictionary: key -> zh-Hans value
# For entries with positional specifiers (e.g. %1$@, %2$@), we keep those intact.
TRANSLATIONS = {
    # Empty/format-only strings
    "": "",
    "-": "-",
    "- %@": "- %@",
    "(%@)": "(%@)",
    "(%lld)": "(%lld)",
    "%@ - %@": "%1$@ - %2$@",
    "%@ ready": "%@ 已就绪",
    "%@, %@": "%1$@，%2$@",
    "%@, %lld entries": "%1$@，%2$lld 条记录",
    "%@, %lld plugins": "%1$@，%2$lld 个插件",
    "%@s - %@s processing": "%1$@s - %2$@s 处理中",
    "%d Prompts": "%d 个提示词",
    "%d Snippets": "%d 个文本片段",
    "%d terms": "%d 个术语",
    "%lld": "%lld",
    "%lld %@": "%1$lld %2$@",
    "%lld %@ (%lld %@)": "%1$lld %2$@（%3$lld %4$@）",
    "%lld days ago": "%lld 天前",
    "%lld hr ago": "%lld 小时前",
    "%lld items selected": "已选择 %lld 项",
    "%lld min ago": "%lld 分钟前",
    "%lld storage plugin(s) active": "%lld 个存储插件已激活",
    "%lld/%lld": "%1$lld/%2$lld",
    "%lld%%": "%lld%%",
    "%lldh %lldm": "%1$lld小时 %2$lld分钟",
    "%lldm": "%lld分钟",

    # Copyright
    "© 2024-2026 TypeWhisper Contributors": "© 2024-2026 TypeWhisper 贡献者",

    # Time placeholder
    "1:23": "1:23",
    "30 days": "30 天",
    "60 days": "60 天",
    "90 days": "90 天",
    "180 days": "180 天",

    # Dictionary
    "Aa": "Aa",

    # Navigation
    "About": "关于",
    "Accessibility": "辅助功能",
    "Accessibility access is required to paste text into other apps.": "需要辅助功能权限才能将文本粘贴到其他应用。",
    "Accessibility access required": "需要辅助功能权限",
    "Action Target": "动作目标",
    "Actions": "动作",
    "Active profile": "当前配置",
    "Active Screen": "活动屏幕",
    "Activity": "活动",
    "Add": "添加",
    "Add Correction": "添加纠正",
    "Add Files...": "添加文件…",
    "Add new prompt": "添加新提示词",
    "Add new snippet": "添加新文本片段",
    "Add Profile": "添加配置",
    "Add Prompt": "添加提示词",
    "Add Snippet": "添加文本片段",
    "Add Term": "添加术语",
    "Advanced": "高级",
    "Advanced automation interface for local tools. Disabled by default and bound to 127.0.0.1 only.": "本地工具的高级自动化接口。默认禁用，仅绑定到 127.0.0.1。",
    "Affects only TypeWhisper recordings and transcriptions, not your live meeting microphone.": "仅影响 TypeWhisper 的录音和转写，不影响实时会议麦克风。",
    "After 1 hour": "1 小时后",
    "After 2 minutes": "2 分钟后",
    "After 5 minutes": "5 分钟后",
    "After 10 minutes": "10 分钟后",
    "After 30 minutes": "30 分钟后",
    "Aggressiv": "激进",
    "AI prompts can rewrite, translate, or summarize.": "AI 提示词可以重写、翻译或总结文本。",
    "All": "全部",
    "All Apps": "所有应用",
    "All available plugins are already installed.": "所有可用插件均已安装。",
    "All presets imported": "所有预设已导入",
    "All Time": "全部时间",
    "Also Installed": "已安装",
    "Always visible": "始终可见",
    "API key configured": "API 密钥已配置",
    "API key required - configure in Integrations tab": "需要 API 密钥 - 在集成选项卡中配置",
    "API Server": "API 服务器",
    "App Language": "应用语言",
    "App-aware formatting": "感知应用的格式化",
    "Appearance": "外观",
    "Apps": "应用",
    "Apps Used": "使用的应用",
    "Are you sure you want to uninstall %@? This will remove the plugin and its data.": "确定要卸载 %@ 吗？这将删除该插件及其数据。",
    "Assign a hotkey to always use this profile, regardless of the active app.": "分配快捷键以始终使用此配置，不受当前活动应用影响。",
    "Audio": "音频",
    "Audio Ducking": "音频闪避",
    "Aus": "关闭",
    "Auto-delete after": "自动删除于",
    "Auto-detect": "自动检测",
    "Auto-unload model": "自动卸载模型",
    "Automatically extracts facts, preferences and patterns from your transcriptions using an LLM. Memories are injected into prompt context.": "使用 LLM 自动从转写内容中提取事实、偏好和模式。记忆会注入到提示词上下文中。",
    "Automatically format transcribed text based on the target app. Configure the output format per profile.": "根据目标应用自动格式化转写文本。可在每个配置中设置输出格式。",
    "Automatically unloads local models from memory after inactivity. It reloads when needed. Does not affect cloud engines.": "在不活动后自动从内存中卸载本地模型。需要时会重新加载。不影响云端引擎。",
    "Available": "可用",
    "Available Plugins": "可用插件",
    "Avg. WPM": "平均 WPM",
    "Back": "返回",
    "Bottom": "底部",
    "Browse Term Packs": "浏览术语包",
    "Browse the Available tab or install from file.": "浏览\u201C可用\u201D选项卡或从文件安装。",
    "Built-in": "内置",
    "Built-in Display": "内置显示器",
    "Cancel": "取消",
    "Cancelled": "已取消",
    "Case sensitive": "区分大小写",
    "Check for Updates...": "检查更新…",
    "Check status:": "检查状态：",
    "Choose a transcription engine. Each engine needs to download a model before it can be used. Open settings to configure.": "选择一个转写引擎。每个引擎在使用前需要下载模型。打开设置进行配置。",
    "Choose Apps": "选择应用",
    "Choose Apps...": "选择应用…",
    "Choose Files...": "选择文件…",
    "Choose how to trigger dictation.": "选择如何触发听写。",
    "Choose how you want to trigger dictation, then record a shortcut.": "选择触发听写的方式，然后录制快捷键。",
    "Clear All": "全部清除",
    "Clear All Data": "清除所有数据",
    "Clear All Memories": "清除所有记忆",
    "Clear All Memories?": "清除所有记忆？",
    "Clear Error Log?": "清除错误日志？",
    "Clear Filters": "清除筛选",
    "Clear search": "清除搜索",
    "Clear shortcut": "清除快捷键",
    "Click the text field below, then press your hotkey and say something!": "点击下方文本框，然后按下快捷键说点什么！",
    "Click to insert": "点击插入",
    "Click to insert a placeholder:": "点击插入占位符：",
    "Clipboard": "剪贴板",
    "Clipboard content": "剪贴板内容",
    "Cloud": "云端",
    "Cloud-based transcription. Requires a free API key.": "基于云端的转写。需要免费的 API 密钥。",
    "Code": "代码",
    "Collapsed": "已折叠",
    "Command Line Tool": "命令行工具",
    "Copied to clipboard": "已复制到剪贴板",
    "Copy": "复制",
    "Copy All Text": "复制全部文本",
    "Correct Text": "正确文本",
    "Correction": "纠正",
    "Corrections": "纠正",
    "Corrections added to dictionary": "纠正已添加到词典",
    "Corrections replace text after transcription": "纠正在转写后替换文本",
    "Create profiles to use app-specific transcription settings.": "创建配置以使用针对特定应用的转写设置。",
    "Create prompts to process your dictated text with AI": "创建提示词，用 AI 处理您的听写文本",
    "Create snippets to automatically expand short triggers into longer text": "创建文本片段，将短触发词自动扩展为更长文本",
    "Current shortcut: %@. Click to change.": "当前快捷键：%@。点击更改。",
    "Daily": "每日",
    "Daily includes stable, release candidate, and daily builds.": "每日版包含稳定版、候选版和每日构建版。",
    "Dashboard": "仪表板",
    "Date": "日期",
    "Default": "默认",
    "Default Engine": "默认引擎",
    "Default LLM Provider": "默认 LLM 提供商",
    "Delete": "删除",
    "Delete %@": "删除 %@",
    "Delete %lld entries": "删除 %lld 条记录",
    "Delete %lld entries matching current filters?": "删除匹配当前筛选条件的 %lld 条记录？",
    "Delete all %lld entries? This cannot be undone.": "删除全部 %lld 条记录？此操作无法撤销。",
    "Delete All Visible": "删除所有可见记录",
    "Delete Entries": "删除记录",
    "Detect spoken instructions in your dictation (e.g., 'write this as an email') and apply them automatically via LLM.": "检测听写中的语音指令（如\u201C将其写为邮件\u201D）并通过 LLM 自动应用。",
    "Deutsch": "德语",
    "Dictated text will appear here.": "听写文本将显示在此处。",
    "Dictation shortcut": "听写快捷键",
    "Dictionary": "词典",
    "Display": "显示",
    "Done": "完成",
    "Downloading %@": "正在下载 %@",
    "Drop audio or video files here": "将音频或视频文件拖放到此处",
    "Dynamic Placeholders": "动态占位符",
    "e.g.": "例如",
    "e.g. addr": "例如 addr",
    "e.g. github.com": "例如 github.com",
    "e.g. kubernetees": "例如 kubernetees",
    "e.g. Kubernetes": "例如 Kubernetes",
    "e.g. Make Formal": "例如 正式化",
    "Echo Handling": "回声处理",
    "Edit": "编辑",
    "Edit %@": "编辑 %@",
    "Edit Correction": "编辑纠正",
    "Edit Profile": "编辑配置",
    "Edit Prompt": "编辑提示词",
    "Edit Snippet": "编辑文本片段",
    "Edit Term": "编辑术语",
    "Enable %@": "启用 %@",
    "Enable API Server": "启用 API 服务器",
    "Enable Memory": "启用记忆",
    "Enable translation": "启用翻译",
    "Engine": "引擎",
    "English": "英语",
    "Enhance": "增强",
    "entries": "条记录",
    "Error": "错误",
    "Error - %@": "错误 - %@",
    "Error Log": "错误日志",
    "Error: %@": "错误：%@",
    "Expanded": "已展开",
    "Export %lld entries as...": "将 %lld 条记录导出为…",
    "Export All": "全部导出",
    "Export All as SRT": "全部导出为 SRT",
    "Export All as VTT": "全部导出为 VTT",
    "Export as...": "导出为…",
    "Export Diagnostics": "导出诊断信息",
    "Export Failed": "导出失败",
    "Export Here": "导出到此处",
    "Export Subtitles": "导出字幕",
    "Extraction Model": "提取模型",
    "Extraction Prompt": "提取提示词",
    "Extraction Provider": "提取提供商",
    "Failed to load plugins.": "加载插件失败。",
    "Fast, private speech-to-text for your Mac. Transcribe with local or cloud engines, process text with AI prompts, and insert directly into any app.": "快速、私密的你 Mac 语音转文字工具。使用本地或云端引擎进行转写，通过 AI 提示词处理文本，并直接插入到任何应用中。",
    "Fastest": "最快",
    "File Transcription": "文件转写",
    "fileTranscription.transcription": "转写",
    "Finish": "完成",
    "Format transcribed text for the target app. Auto-detect chooses the format based on the app's bundle ID. Requires app-aware formatting to be enabled in Recording settings.": "为目标应用格式化转写文本。自动检测根据应用的 Bundle ID 选择格式。需要在录音设置中启用感知应用的格式化。",
    "General": "通用",
    "Get Started": "开始使用",
    "Global Setting": "全局设置",
    "Go to Dashboard": "前往仪表板",
    "Grant Access": "授权访问",
    "Granted": "已授权",
    "Hello, this is a live preview of the streaming text...": "你好，这是流式文本的实时预览…",
    "Helps Whisper recognize technical terms": "帮助 Whisper 识别技术术语",
    "Higher priority profiles take precedence when multiple profiles match.": "当多个配置匹配时，优先级较高的配置优先。",
    "History": "历史记录",
    "Hold to record, release to stop.": "按住录音，松开停止。",
    "Home": "主页",
    "Hotkey": "快捷键",
    "Hotkeys": "快捷键",
    "HTML": "HTML",
    "Hybrid": "混合",
    "I'll try later": "稍后再试",
    "Icon": "图标",
    "Idle": "空闲",
    "Immediate": "立即",
    "Import All": "全部导入",
    "Import Preset": "导入预设",
    "in any app to begin.": "在任意应用中开始。",
    "Indicator": "指示器",
    "Inline Commands": "内联命令",
    "Input Device": "输入设备",
    "Insert Text": "插入文本",
    "Inserting text": "正在插入文本",
    "Install": "安装",
    "Install %@": "安装 %@",
    "Install a transcription engine to get started.": "安装转写引擎以开始使用。",
    "Install additional LLM providers from the Integrations tab.": "从集成选项卡安装其他 LLM 提供商。",
    "Install an LLM provider plugin (e.g. Groq, OpenAI) from the Integrations tab to use prompts.": "从集成选项卡安装 LLM 提供商插件（如 Groq、OpenAI）以使用提示词。",
    "Install Command Line Tool": "安装命令行工具",
    "Install Failed": "安装失败",
    "Install from File...": "从文件安装…",
    "Installed": "已安装",
    "Installed at /usr/local/bin/typewhisper": "已安装到 /usr/local/bin/typewhisper",
    "Installing plugins...": "正在安装插件…",
    "Installing...": "正在安装…",
    "Instead of inserting the LLM result as text, send it to an action plugin.": "将 LLM 结果发送到动作插件，而不是作为文本插入。",
    "Integrations": "集成",
    "JSON (.json)": "JSON (.json)",
    "JSON output:": "JSON 输出：",
    "just_now": "刚刚",
    "Language": "语言",
    "Last 7 Days": "最近 7 天",
    "Last 30 Days": "最近 30 天",
    "Last 90 Days": "最近 90 天",
    "Last Month": "上个月",
    "Later": "稍后",
    "Launch at Login": "登录时启动",
    "Learn More": "了解更多",
    "Left Side": "左侧",
    "Licensed under the GNU General Public License v3.0": "采用 GNU 通用公共许可证 v3.0 授权",
    "List models:": "列出模型：",
    "LLM Provider": "LLM 提供商",
    "LLM Providers": "LLM 提供商",
    "LLM:": "LLM：",
    "Load Presets": "加载预设",
    "Loading": "加载中",
    "Local": "本地",
    "M4A": "M4A",
    "Markdown": "Markdown",
    "Markdown (.md)": "Markdown (.md)",
    "Memory": "记忆",
    "Menu bar icon hidden": "菜单栏图标已隐藏",
    "Microphone": "麦克风",
    "Microphone access is required for dictation.": "听写功能需要麦克风权限。",
    "Microphone access is required to continue.": "需要麦克风权限才能继续。",
    "Microphone access required": "需要麦克风权限",
    "Microphone disconnected": "麦克风已断开",
    "Microphone disconnected. Falling back to system default.": "麦克风已断开。回退到系统默认。",
    "Min. text length": "最小文本长度",
    "Mittel": "中等",
    "Model": "模型",
    "Month": "月",
    "Name": "名称",
    "Name and prompt cannot be empty": "名称和提示词不能为空",
    "Never": "从不",
    "New Correction": "新建纠正",
    "New Profile": "新建配置",
    "New Prompt": "新建提示词",
    "New Snippet": "新建文本片段",
    "New Term": "新建术语",
    "Next": "下一步",
    "No activity in this period.": "此时间段内没有活动。",
    "No apps assigned": "未分配应用",
    "No dictionary entries": "没有词典条目",
    "No Entries": "无记录",
    "No entries for this filter": "此筛选条件下没有记录",
    "No errors recorded.": "没有记录到错误。",
    "No hotkey is configured. Go back to set one up.": "未配置快捷键。请返回设置。",
    "No hotkey set. You won't be able to start dictation without one.": "未设置快捷键。没有快捷键将无法启动听写。",
    "No matching prompts": "没有匹配的提示词",
    "No memory storage plugins active. Enable one in Integrations.": "没有活动的记忆存储插件。请在集成中启用。",
    "No model loaded": "未加载模型",
    "No plugins installed.": "未安装插件。",
    "No Profiles": "无配置",
    "No prompts yet": "暂无提示词",
    "No results for the active filters.": "当前筛选条件下没有结果。",
    "No snippets yet": "暂无文本片段",
    "No speech detected": "未检测到语音",
    "No speech recognized": "未识别到语音",
    "No transcription engine is ready. Go back to set one up.": "没有转写引擎就绪。请返回设置。",
    "No transcription engines available.": "没有可用的转写引擎。",
    "No transcription engines installed. Install engines via Integrations.": "未安装转写引擎。请通过集成安装引擎。",
    "No transcriptions yet.": "暂无转写记录。",
    "No URL patterns": "无 URL 模式",
    "noLLMProvider": "未配置 LLM 提供商。请在设置中配置 Apple Intelligence 或 API 密钥。",
    "None": "无",
    "Not available - Apple Intelligence must be enabled in System Settings": "不可用 - 需要在系统设置中启用 Apple Intelligence",
    "Not configured": "未配置",
    "Not installed": "未安装",
    "not ready": "未就绪",
    "Not running": "未运行",
    "Notch": "刘海",
    "OK": "好",
    "Older": "更早",
    "Older entries are automatically removed at app launch.": "较旧的记录会在应用启动时自动删除。",
    "Only during activity": "仅在活动时",
    "Open an engine's settings to download a model.": "打开引擎设置以下载模型。",
    "Open in Raycast": "在 Raycast 中打开",
    "Open Integrations": "打开集成",
    "Open Plugins Folder": "打开插件文件夹",
    "or": "或",
    "Original text cannot be empty": "原始文本不能为空",
    "Output Format": "输出格式",
    "Output Formatting": "输出格式化",
    "Overlay": "悬浮窗",
    "Override the default provider for this prompt. Leave on \"Default\" to use the global setting.": "覆盖此提示词的默认提供商。保留\"默认\"以使用全局设置。",
    "Overrides": "覆盖",
    "Palette shortcut": "调色板快捷键",
    "Pause": "暂停",
    "Pending": "等待中",
    "Percentage of your current volume to use during recording. 0% mutes completely.": "录音时使用当前音量的百分比。0% 为完全静音。",
    "Permissions": "权限",
    "Pipe to clipboard:": "管道输出到剪贴板：",
    "Plain Text": "纯文本",
    "Plain Text (.txt)": "纯文本 (.txt)",
    "Play": "播放",
    "Play sound feedback": "播放声音反馈",
    "Playback position": "播放位置",
    "Plays a sound when recording starts and when transcription completes.": "在录音开始和转写完成时播放声音。",
    "Plugin": "插件",
    "Plugin incompatible with this macOS version": "插件与当前 macOS 版本不兼容",
    "Plugins": "插件",
    "Position": "位置",
    "Post-Processors": "后处理器",
    "Pre-built collections of technical terms for common domains": "常见领域的预构建技术术语集合",
    "Preserve clipboard content": "保留剪贴板内容",
    "preset.actionItems": "提取待办事项",
    "preset.createTable": "创建表格",
    "preset.draftEmail": "起草邮件",
    "preset.formatAsList": "格式化为列表",
    "preset.jsonData": "JSON 数据",
    "preset.meetingNotes": "会议记录",
    "preset.reply": "回复",
    "preset.translate": "翻译",
    "preset.writeEmail": "撰写邮件",
    "Press": "按下",
    "Press %@ in any app to get started.": "在任意应用中按下 %@ 开始使用。",
    "Press a hotkey and talk naturally in any app.": "按下快捷键，在任意应用中自然说话。",
    "Press a key…": "按下一个键…",
    "Press to start, press again to stop.": "按下开始，再按一次停止。",
    "Primary Screen": "主屏幕",
    "Priority": "优先级",
    "Processing prompt": "正在处理提示词",
    "Processing prompt: %@": "正在处理提示词：%@",
    "Processing transcription": "正在处理转写",
    "Processing...": "处理中…",
    "Profile": "配置",
    "Profile name": "配置名称",
    "Profile shortcut": "配置快捷键",
    "Profiles": "配置",
    "Prompt": "提示词",
    "Prompt complete": "提示词已完成",
    "Prompt Palette": "提示词面板",
    "Prompts": "提示词",
    "Provider": "提供商",
    "Push-to-Talk": "按键说话",
    "Quit": "退出",
    "Raycast Extension": "Raycast 扩展",
    "Read Back Last Transcription": "朗读上次转写",
    "Reads back the transcribed text via speech synthesis after each dictation.": "每次听写后通过语音合成朗读转写文本。",
    "Ready": "就绪",
    "Ready to start dictating?": "准备好开始听写了吗？",
    "Recent Transcriptions": "最近转写",
    "Recommended": "推荐",
    "Recommended for pasting text into other apps. You can grant this later.": "推荐用于将文本粘贴到其他应用。您可以稍后授权。",
    "Record Shortcut": "录制快捷键",
    "Record shortcut for %@": "为 %@ 录制快捷键",
    "recorder.copyTranscript": "复制转写",
    "recorder.delete": "删除",
    "recorder.duration": "时长",
    "recorder.format": "输出格式",
    "recorder.hasTranscript": "转写内容",
    "recorder.language": "语言",
    "recorder.liveTranscript": "实时转写",
    "recorder.liveTranscriptActive": "实时转写窗口已激活",
    "recorder.liveTranscriptHint": "在集成中安装实时转写插件以获取实时转写窗口。",
    "recorder.liveTranscription": "实时转写",
    "recorder.mic": "麦克风",
    "recorder.noEngine": "未选择引擎",
    "recorder.noRecordings": "暂无录音",
    "recorder.recordings": "录音",
    "recorder.revealInFinder": "在 Finder 中显示",
    "recorder.showTranscript": "显示转写",
    "recorder.sources": "音频源",
    "recorder.startRecording": "开始录音",
    "recorder.stopRecording": "停止录音",
    "recorder.systemAudio": "系统音频",
    "recorder.systemAudioPermission": "系统音频录制需要屏幕录制权限。",
    "recorder.transcribe": "转写",
    "recorder.transcribing": "正在转写…",
    "recorder.transcription": "转写",
    "Recording": "录音",
    "Recording Indicator": "录音指示器",
    "Recording shortcut - press a key or Escape to cancel": "录制快捷键 - 按下按键或按 Escape 取消",
    "Recording started": "录音已开始",
    "Recording timer": "录音计时器",
    "Recording...": "正在录音…",
    "Reduce system volume during recording": "录音时降低系统音量",
    "Release Candidate": "候选版",
    "Release Candidate includes stable and preview builds.": "候选版包含稳定版和预览版。",
    "Remove %@": "移除 %@",
    "Replacement": "替换",
    "Replacement text cannot be empty for corrections": "纠正的替换文本不能为空",
    "Replaces incorrect transcriptions": "替换错误的转写",
    "Required": "必需",
    "Requires the API server to be running.": "需要 API 服务器正在运行。",
    "Requires the API server to be running. The CLI tool connects to TypeWhisper's API for fast transcription without model cold starts.": "需要 API 服务器正在运行。CLI 工具连接到 TypeWhisper 的 API 以实现快速转写，无需模型冷启动。",
    "Reset to Default": "恢复默认",
    "Restart Now": "立即重启",
    "Restart Required": "需要重启",
    "Restores your clipboard after text insertion. Without this, your clipboard contains the transcribed text after dictation.": "在插入文本后恢复剪贴板内容。不启用此选项，听写后剪贴板将包含转写文本。",
    "Retry": "重试",
    "Right Side": "右侧",
    "Right-click to export or delete selected entries.": "右键点击以导出或删除选中的记录。",
    "Run setup again": "重新运行设置",
    "Running on port %@": "运行在端口 %@",
    "Runs locally on your Mac. No API key needed.": "在 Mac 上本地运行。无需 API 密钥。",
    "Save": "保存",
    "Save audio with transcriptions": "保存音频与转写",
    "Search apps...": "搜索应用…",
    "Search prompts": "搜索提示词",
    "Search prompts...": "搜索提示词…",
    "Search...": "搜索…",
    "Seed Demo Data": "生成演示数据",
    "Select a plugin bundle or ZIP file to install.": "选择要安装的插件包或 ZIP 文件。",
    "Select an extraction provider to start collecting memories.": "选择提取提供商以开始收集记忆。",
    "Select text in any app, press the shortcut, and choose a prompt to process the text.": "在任意应用中选择文本，按下快捷键，然后选择提示词处理文本。",
    "Select your preferred microphone:": "选择您偏好的麦克风：",
    "Selected": "已选择",
    "Settings": "设置",
    "Settings for %@": "%@ 的设置",
    "Settings...": "设置…",
    "settings.showRecorderTab": "显示录音机选项卡",
    "settings.showRecorderTab.description": "显示录音机选项卡，用于录制麦克风和系统音频。",
    "settings.tab.recorder": "录音机",
    "settings.tab.watchFolder": "监视文件夹",
    "Setup": "设置向导",
    "Short press to toggle, hold to push-to-talk.": "短按切换，长按按键说话。",
    "Shortcut": "快捷键",
    "Show help:": "显示帮助：",
    "Show in Finder": "在 Finder 中显示",
    "Show menu bar icon": "显示菜单栏图标",
    "Show terms for %@": "显示 %@ 的术语",
    "Skip Setup": "跳过设置",
    "Snippet": "文本片段",
    "Snippets": "文本片段",
    "Sound": "声音",
    "Speak": "说话",
    "Spoken feedback": "语音反馈",
    "Spoken language": "口语语言",
    "Spoken Language": "口语语言",
    "SRT": "SRT",
    "Stable": "稳定版",
    "Stable gets production releases only.": "稳定版仅提供正式发布版本。",
    "Start dictation, search history and switch profiles directly from Raycast.": "直接从 Raycast 开始听写、搜索历史记录和切换配置。",
    "Startup": "启动",
    "Step %lld of %lld": "第 %1$lld 步，共 %2$lld 步",
    "Stop Preview": "停止预览",
    "Stores a WAV recording alongside each transcription. Uses approximately 1 MB per 30 seconds.": "在每次转写时保存 WAV 录音。每 30 秒约占用 1 MB。",
    "Streaming text": "流式文本",
    "Style": "样式",
    "Subdomains are included automatically. E.g. \"google.com\" also matches \"docs.google.com\".": "子域名会自动包含。例如，\"google.com\" 也匹配 \"docs.google.com\"。",
    "System Default": "系统默认",
    "System Prompt": "系统提示词",
    "tap again for double-tap…": "再次按下以双击…",
    "Target": "目标",
    "Target language": "目标语言",
    "Task": "任务",
    "Term": "术语",
    "Term Packs": "术语包",
    "Terms": "术语",
    "Terms are sent to the transcription service for better recognition": "术语会发送到转写服务以获得更好的识别效果",
    "Terms help speech recognition identify technical words correctly. Corrections fix common transcription mistakes automatically.": "术语帮助语音识别正确识别技术词汇。纠正会自动修复常见的转写错误。",
    "Test Microphone": "测试麦克风",
    "Text inserted": "文本已插入",
    "Text replaced": "文本已替换",
    "The language being spoken. Setting this explicitly improves accuracy.": "正在使用的口语语言。明确设置可提高准确率。",
    "The language change will take effect after restarting TypeWhisper.": "语言更改将在重启 TypeWhisper 后生效。",
    "The notch indicator extends the MacBook notch area to show recording status.": "刘海指示器扩展 MacBook 刘海区域以显示录音状态。",
    "The overlay indicator appears as a floating pill on the screen.": "悬浮窗指示器在屏幕上显示为浮动胶囊。",
    "This hotkey is also assigned to the %@ slot.": "此快捷键也已分配给 %@ 位置。",
    "This Week": "本周",
    "This will permanently delete all recorded errors.": "这将永久删除所有已记录的错误。",
    "This will permanently delete all stored memories from all plugins. This cannot be undone.": "这将永久删除所有插件中存储的所有记忆。此操作无法撤销。",
    "Time": "时间",
    "Time Saved": "节省时间",
    "Timer": "计时器",
    "To use AI prompts, install an LLM provider (e.g. Groq, OpenAI) from the Integrations tab after setup.": "要使用 AI 提示词，请在设置完成后从集成选项卡安装 LLM 提供商（如 Groq、OpenAI）。",
    "Today": "今天",
    "Toggle": "切换",
    "Top": "顶部",
    "total": "总计",
    "Transcribe": "转写",
    "Transcribe All": "全部转写",
    "Transcribe audio:": "转写音频：",
    "Transcribe File...": "转写文件…",
    "Transcribe with language:": "使用语言转写：",
    "Transcribing": "正在转写",
    "Transcribing...": "正在转写…",
    "Transcription": "转写",
    "Transcription complete, %lld words": "转写完成，%lld 个词",
    "Transcription Engine": "转写引擎",
    "Transcription Engines": "转写引擎",
    "Transcriptions shorter than this are skipped for memory extraction.": "短于此长度的转写将跳过记忆提取。",
    "Translate to English": "翻译为英语",
    "Translation": "翻译",
    "Trigger": "触发词",
    "Trigger and replacement cannot be empty": "触发词和替换内容不能为空",
    "Try Again": "重试",
    "Try It Out": "试一试",
    "Type": "输入",
    "TypeWhisper": "TypeWhisper",
    "TypeWhisper Dev": "TypeWhisper 开发版",
    "TypeWhisper is ready to use in any app.": "TypeWhisper 已准备就绪，可在任何应用中使用。",
    "TypeWhisper will start automatically when you log in.": "TypeWhisper 将在您登录时自动启动。",
    "TypeWhisper works with Raycast. Start dictation and more directly from your launcher.": "TypeWhisper 支持 Raycast。直接从启动器开始听写等操作。",
    "Uninstall": "卸载",
    "Uninstall %@": "卸载 %@",
    "Uninstall Plugin": "卸载插件",
    "Unlimited": "无限制",
    "Update": "更新",
    "Update Channel": "更新频道",
    "Updates": "更新",
    "URL Patterns": "URL 模式",
    "Usage Examples": "使用示例",
    "Uses Apple Translate (on-device)": "使用 Apple 翻译（设备端）",
    "Utilities": "工具",
    "v%@": "v%@",
    "Version %@ (%@)": "版本 %1$@（%2$@）",
    "Version %@ (%@)%@": "版本 %1$@（%2$@）%3$@",
    "Visibility": "可见性",
    "Voice-powered typing for your Mac": "语音驱动的 Mac 输入",
    "VTT": "VTT",
    "watchFolder.autoStart": "应用启动时开始监视",
    "watchFolder.deleteSource": "转写后删除源文件",
    "watchFolder.description": "监视所选文件夹中的新音频文件并自动转写。",
    "watchFolder.engine": "引擎",
    "watchFolder.engine.default": "默认（全局选择）",
    "watchFolder.folders": "文件夹",
    "watchFolder.history": "处理历史",
    "watchFolder.history.clear": "清除历史",
    "watchFolder.history.empty": "尚未处理任何文件。",
    "watchFolder.language": "语言",
    "watchFolder.language.auto": "自动检测",
    "watchFolder.model.default": "默认模型",
    "watchFolder.noFolder": "未选择文件夹",
    "watchFolder.outputFolder": "输出文件夹",
    "watchFolder.outputFolder.sameAsWatch": "与监视文件夹相同",
    "watchFolder.outputFormat": "输出格式",
    "watchFolder.plainText": "纯文本 (.txt)",
    "watchFolder.selectFolder": "选择文件夹…",
    "watchFolder.selectFolder.message": "选择要监视音频文件的文件夹",
    "watchFolder.selectOutputFolder.message": "选择转写输出的文件夹",
    "watchFolder.settings": "设置",
    "watchFolder.startWatching": "开始监视",
    "watchFolder.stopWatching": "停止监视",
    "watchFolder.watchFolder": "监视文件夹",
    "WAV": "WAV",
    "WAV, MP3, M4A, FLAC, MP4, MOV": "WAV、MP3、M4A、FLAC、MP4、MOV",
    "Waveform": "波形",
    "Week": "周",
    "Welcome to TypeWhisper": "欢迎使用 TypeWhisper",
    "When a prompt is assigned, dictated text will be processed by the LLM before insertion. This replaces translation.": "分配提示词后，听写文本将在插入前由 LLM 处理。这将替代翻译功能。",
    "When enabled, transcriptions from this profile are stored as memories and used as context for prompts.": "启用后，此配置的转写将作为记忆存储，并用作提示词的上下文。",
    "When hidden, the app is accessible via the Dock icon.": "隐藏后，可通过 Dock 图标访问应用。",
    "words": "词",
    "Words": "词数",
    "Works Offline": "离线可用",
    "Wrong Text": "错误文本",
    "yesterday": "昨天",
    "Yesterday": "昨天",
    "You can access TypeWhisper settings via the Dock icon.": "您可以通过 Dock 图标访问 TypeWhisper 设置。",
    "You can install more engines from the Integrations tab after setup.": "设置完成后，您可以从集成选项卡安装更多引擎。",
    "You have a transcription engine ready.": "您已有一个就绪的转写引擎。",
    "You're all set!": "一切就绪！",
    "Your activity will appear here after your first transcription.": "首次转写后，您的活动将显示在此处。",
    "Your words appear as text instantly.": "您的话语会即时转为文字。",
}

# Special handling: %d Prompts has plural variations
PLURAL_TRANSLATIONS = {
    "%d Prompts": {
        "one": "%d 个提示词",
        "other": "%d 个提示词"
    }
}


def main():
    # Read the file
    with open(FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    count_added = 0
    count_skipped = 0
    missing_keys = []

    strings = data.get("strings", {})

    for key, value in strings.items():
        # Check if zh-Hans already exists
        localizations = value.get("localizations", {})
        if "zh-Hans" in localizations:
            count_skipped += 1
            continue

        # Look up translation
        if key not in TRANSLATIONS:
            missing_keys.append(key)
            continue

        translation = TRANSLATIONS[key]

        # Ensure localizations dict exists
        if "localizations" not in value:
            value["localizations"] = {}

        # Handle plural variations for %d Prompts
        if key in PLURAL_TRANSLATIONS:
            value["localizations"]["zh-Hans"] = {
                "variations": {
                    "plural": {}
                }
            }
            for plural_form, plural_value in PLURAL_TRANSLATIONS[key].items():
                value["localizations"]["zh-Hans"]["variations"]["plural"][plural_form] = {
                    "stringUnit": {
                        "state": "translated",
                        "value": plural_value
                    }
                }
        else:
            # Regular string unit
            value["localizations"]["zh-Hans"] = {
                "stringUnit": {
                    "state": "translated",
                    "value": translation
                }
            }

        count_added += 1

    # Write back
    with open(FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Added zh-Hans translations for {count_added} strings.")
    print(f"Skipped {count_skipped} strings (already had zh-Hans).")
    if missing_keys:
        print(f"WARNING: {len(missing_keys)} keys not found in translation dict:")
        for k in missing_keys:
            print(f"  - {repr(k)}")

    # Verify: count total strings and those with zh-Hans
    total = len(strings)
    with_zh = sum(1 for v in strings.values() if "zh-Hans" in v.get("localizations", {}))
    print(f"\nVerification: {with_zh}/{total} strings now have zh-Hans translations.")


if __name__ == "__main__":
    main()
